[project]
name = "nexus-backend"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "fastapi[standard]",
    "sqlalchemy>=2.0.35",
    "pydantic>=2.9.2",
    "python-dotenv>=1.0.1",
    "anthropic>=0.122.0",
    "pyjwt>=2.9.0",
    "email-validator>=2.2.0",
]

[tool.fastapi]
entrypoint = "app.main:app"

[tool.setuptools.packages.find]
include = ["app*"]
